### ISSUE TITLE
Points of interest

### ISSUE THREAD

**Issue by waynewccheng** [plemaillet/read_spectral_data#2]
https://github.com/plemaillet/read_spectral_data/blob/4ef44f167fcb5f957c7adb979f4a46ed6d48713b/ExampleCode.m#L43

Jocelyne: I'm unsure why (500,500) and (400,400) are chosen for transmittance curves/sample values. Are the pixels to be chosen arbitrarily, or is there significance in these two points?

WCC: I think we can use the points of interest that Jocelyn and Mary identified previously.

**Comment by plemaillet** [comment]
OK, I chose these at random. What are the points they identify?

**Comment by plemaillet** [comment]
OK, I chose these at random, I can change them. What are the points they identified?

**Comment by liu-jocel** [comment]
Hi Paul, 
I don't have access to the code that identified the original pixels of interest, but I do still have the histological structure classifications and the eight truth images, so I can re-identify those points and get back to you later.

**Comment by plemaillet** [comment]
Thanks Jocelyne

**Comment by waynewccheng** [comment]
> https://github.com/plemaillet/read_spectral_data/blob/4ef44f167fcb5f957c7adb979f4a46ed6d48713b/ExampleCode.m#L43
> 
> Jocelyne: I'm unsure why (500,500) and (400,400) are chosen for transmittance curves/sample values. Are the pixels to be chosen arbitrarily, or is there significance in these two points?
> 
> WCC: I think we can use the points of interest that Jocelyn and Mary identified previously.

Added the 3 points annotated by Jocelyn and Mary in README. Hope it is easier for you to find the location.

**Comment by liu-jocel** [comment]
Thanks! Identified pixels of interest (including description) for all samples are below:

**Bladder:**
[683 261] (superficial umbrella cells)
[621 271] (intermediate urothelial cells)
[325 372] (connective tissue)
[451 326] (basal urothelial cells)

**Uterine Cervix:**
[266 52] (superficial cells)
[559 184] (intermediate cells)
[337 266] (basal cells)
[416 319] (stroma)

**Brain:**
[484 498] (blood vessel, RBC's)
[364  376] (neuron)
[452 357] (neuropil)

**Breast:**
[360 433] (connective tissue)
[142 211] (epithelial cells)

**Colon:**
[762 618] (RBC's)
[763 477] (muscularis mucosa)
[598 545] (epithelial cells, glandular)
[338 177] (laminar propria)

**Kidney:**
[250 594] (RBC's)
[203 344] (tubule, cytoplasm)
[256, 491] (glomerulus, nucleus)
[371 431] (glomerulus, cytoplasm)
[196 337] (tubule, nucleus)

**Liver:**
[577 477] (hepatocyte, nucleus)
[599 446] (hepatocyte, cytoplasm)

**Lung:**
[673 537] (blood vessel, RBC's)
[467 401] (alveolar walls, cytoplasm)
[590 406] (alveolar walls, nuclei)

**Comment by waynewccheng** [comment]
Thanks! Added to ExampleCode.m

**Comment by plemaillet** [comment]
Thanks Jocelyne. These are for the images as displayed ion the draft paper you wrote, is that correct?
Some of the images are upside-down compared to the one I measured so I just want to make sure.

**Comment by liu-jocel** [comment]
The points are determined from the images Dr. Cheng recently shared with me (Processed data, 031320): 
https://drive.google.com/drive/folders/1Vb7YBf7LKBGaPfW7_3whz72e4AEboRSX?usp=sharing
Please let me know if there are any issues!

**Comment by plemaillet** [comment]
Thanks Jocelyne. These are the same images I am working on.
